name: Local AI Remodeler (Ollama + Aider)

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      task:
        description: "Describe la remodelación a realizar"
        required: false
        default: ""

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  remodel:
    # Asegúrate de que tu runner es Windows; los self-hosted traen estas labels por defecto
    runs-on: [self-hosted, Windows]
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issue_comment' &&
       (contains(github.event.comment.body, '/remodel') || contains(github.event.comment.body, '/refactor')))
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Usa Windows PowerShell clásico
      - name: Ensure Ollama is running (Windows)
        shell: powershell
        run: |
          $ollamaExe = "C:\Users\exsal\AppData\Local\Programs\Ollama\ollama.exe"
          if (-not (Test-Path $ollamaExe)) {
            Write-Error "No se encontró: $ollamaExe"; exit 1
          }

          # Arranca el servidor si no está
          $p = Get-Process -Name "ollama" -ErrorAction SilentlyContinue
          if (-not $p) {
            Start-Process -FilePath $ollamaExe -ArgumentList "serve" -WindowStyle Hidden
            Start-Sleep -Seconds 3
          }

          # Verifica y baja el modelo (idempotente)
          & $ollamaExe list | Out-Null
          try { & $ollamaExe pull qwen2.5-coder:7b } catch { }


      - name: Ensure Aider is available (Windows)
        shell: powershell
        run: |
          if (-not (Get-Command aider -ErrorAction SilentlyContinue)) {
            py -m pip install --user aider-chat==0.59.1
            "$env:USERPROFILE\AppData\Roaming\Python\Python311\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Append
          }
          aider --version

      - name: Run Local Remodel (PowerShell)
        shell: powershell
        env:
          INPUT_TASK: ${{ github.event.inputs.task }}
          COMMENT: ${{ github.event.comment.body }}
        run: |
          if (-not (Test-Path "tools/local-remodel.ps1")) {
            Write-Error "Falta tools/local-remodel.ps1"
            exit 1
          }
          powershell -ExecutionPolicy Bypass -File tools/local-remodel.ps1
